targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/src/api/swagger/'
          output_folder: 'lib/src/api/swagger/generated/'
          separate_models: true
          build_only_models: true
          override_equals_and_hashcode: false
          override_to_string: false